name: Benchmark XGI
on:
  push:
    branches:
      - main
      - test-benchmark-units
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run XGI benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      
      - name: Install packages
        run: |
          pip install --upgrade pip
          pip install .[benchmark]
      
      - name: Run benchmarks
        run: |
          echo "Running benchmarks from branch: ${GITHUB_REF#refs/heads/}"
          pytest benchmarks/*.py --benchmark-json benchmarks/output.json --benchmark-only
      
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: "pytest"
          output-file-path: benchmarks/output.json
          gh-pages-branch: "gh-pages"
          benchmark-data-dir-path: "dev/bench"
          github-token: ${{ secrets.GITHUB_TOKEN}}
          auto-push: true
          alert-threshold: '200%'
          fail-on-alert: true
          comment-on-alert: false
          